### ISSUE TITLE
fix some ui issues

### ISSUE THREAD

**Issue by angelsoft-oscar** [angelsoft-oscar/freelance-resume-foliox#2]
1. Fix scroll bar issue when you open the thumbnail of portfolio
2. Fix JavaScript issue when you click an item of portfolio

**Comment by chenkang-secret** [comment]
1. added the ? mark for undefined variables.
2. add some css lines for scrollbar
::-webkit-scrollbar {
  width: 11px;
}
body {
  scrollbar-width: thin;
  scrollbar-color: var(--extra-color) #1e1345;
}
:-webkit-scrollbar-track {
  background: #1e1345;
}
::-webkit-scrollbar-thumb {
  background-color: var(--extra-color);
  border-radius: 6px;
  border: 3px solid #1e1345;
}
